scrape_configs:
  - job_name: 'test-jmeter-monitoring'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'jmeter'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9270']